version: '3'

services:
    web:
        build: ./
        tty: true
        ports:
            - 8010:8010
        environment:
            FLASK_ENV: development
            TZ: Asia/Tokyo
        volumes:
            - ./src:/app